---
# tasks file for lighthouse-role
- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes force_apt_get=yes

- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx

- name: Clone a github repository
  git:
    repo: '{{ lighthouse_repo }}'
    dest: ./git
    clone: yes
    update: yes

- name: copy files
  become: true
  command: cp ./git/. /var/www/html/ -r
